### ISSUE TITLE
1.5.1: new query takes long time on TEST

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-dedupe#106]
`https://test.datim.org/api/sqlViews/wzpSd6j89wc/data?cacheBuster=1577817986700&paging=false&var=ou:XOivy2uDpMF&var=pe:2019Q3&var=rs:false&var=ps:50&var=pg:1&var=dt:RESULTS&var=ty:PURE&var=ag:NONE&var=dg:NONE`

**Comment by jakub-bao** [comment]
Seems like to be something with cache.. it's just fine now...

**Comment by jakub-bao** [comment]
@jason-p-pickering The query is sometime taking really long time on TEST ...

`https://test.datim.org/api/sqlViews/wzpSd6j89wc/data?cacheBuster=1577819176523&paging=false&var=ou:XOivy2uDpMF&var=pe:2019Q3&var=rs:false&var=ps:50&var=pg:1&var=dt:RESULTS&var=ty:PURE&var=ag:NONE&var=dg:NONE`

Can you take a look into it?

**Comment by jason-p-pickering** [comment]
I had a look, but do not think its unusual. This query does take a long time, and is strongly dependent on the speed of the box. At this point, its going to be difficult to speed this up, until we adopt a much different approach. So for now, I suggest closing this as "won't fix"
