### ISSUE TITLE
2.33 Newrelease: ERROR: column "value" does not exist

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-dedupe#107]
Original ticket here: https://github.com/pepfar-datim/Global/issues/5710

The dedupe app is not working on newrelease:

![image](https://user-images.githubusercontent.com/47790868/71634421-ef46f280-2be9-11ea-93ea-f38180034e1a.png)

`"ERROR: column \"value\" does not exist\n  Hint: Perhaps you meant to reference the column \"keyjsonvalue.jbvalue\".\n  Where: PL/pgSQL function view_duplicates(character,character varying,boolean,integer,integer,character varying,character varying,character varying,character varying) line 140 at EXECUTE"`

Link: https://newrelease.datim.org/api/sqlViews/wzpSd6j89wc/data?cacheBuster=1577826312424&paging=false&var=ou:XOivy2uDpMF&var=pe:2019Q3&var=rs:false&var=ps:50&var=pg:1&var=dt:RESULTS&var=ty:PURE&var=ag:NONE&var=dg:NONE

**Comment by jason-p-pickering** [comment]
Should be fixed on the latest version of the code.
