### ISSUE TITLE
Filter by technical area not working

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-dedupe#110]
After deployment of the new filtersm, @jason-p-pickering noticed that the app doesn't filter dedupes by tech area. Instead, it returns all the results. It seems like there will be an issue within the SQL script.

cc @benguaraldi

**Comment by benguaraldi** [comment]
Thanks, @jakub-bao.

@jason-p-pickering, let me know if you want someone on my team to look into this.

**Comment by benguaraldi** [comment]
@DavidNesbitt2020 I suspect that this is fixed in the new app, but could you check?

**Comment by DavidNesbitt2020** [comment]
@benguaraldi and @jakub-bao this appears resolved in the new app on ben.datim:

pre-test:
![image](https://user-images.githubusercontent.com/73136568/102399480-b052ae00-3fae-11eb-88dc-2c8f74d318c4.png)

Filtered by TA (HTS_RECENT):
![image](https://user-images.githubusercontent.com/73136568/102399619-d8421180-3fae-11eb-9abe-08fd16594a08.png)

Filtered by a different TA (OVC_SERV)
![image](https://user-images.githubusercontent.com/73136568/102399779-12131800-3faf-11eb-9976-99f0c7e71f63.png)

**Comment by benguaraldi** [comment]
Great!  Thanks, @DavidNesbitt2020!
