### ISSUE TITLE
2.33 Header Bar

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-dedupe#111]
I've got stuck by having issues running Datim Dedupe locally:
![image](https://user-images.githubusercontent.com/47790868/73017820-6f7a0580-3dee-11ea-9ded-b773ca808405.png)

**Comment by jakub-bao** [comment]
It's a credentials issue...

**Comment by jakub-bao** [comment]
finally working
![image](https://user-images.githubusercontent.com/47790868/73018234-34c49d00-3def-11ea-922a-5d0e86b86ad1.png)

**Comment by jakub-bao** [comment]
I've removed the angular header bar...

![image](https://user-images.githubusercontent.com/47790868/73090115-b840c580-3ea5-11ea-8f59-427205b8c824.png)

And I've got a build process setup to add react code

![image](https://user-images.githubusercontent.com/47790868/73090178-d4dcfd80-3ea5-11ea-93a5-873eb31910a7.png)

Now the trick will be to use `react` & `dhis2 header bar` to work together and render on top of the page:

![image](https://user-images.githubusercontent.com/47790868/73090238-f9d17080-3ea5-11ea-9e96-9f59f84add4c.png)

I'll try to use a minimalistic REACT setup without webpack or JSX.

**Comment by jakub-bao** [comment]
tutorial here: https://reactjs.org/docs/react-without-jsx.html

**Comment by jakub-bao** [comment]
OK, I got the infrastructure working. Now I should be able to add the real blue thing...

It's a homebrew smallest possible react deployment without JSX or WebPack or Babel...

`<script>` includes instead of es6 `imports`:
![image](https://user-images.githubusercontent.com/47790868/73099298-365a9780-3eb9-11ea-836d-4e6cfd613187.png)

Plain JavaScript instead of JSX:
![image](https://user-images.githubusercontent.com/47790868/73099322-45414a00-3eb9-11ea-915b-8ca02b65a1ea.png)

And it's suprisingly rendering (a placeholder):
![image](https://user-images.githubusercontent.com/47790868/73099369-63a74580-3eb9-11ea-979a-aaaf9471f8ab.png)


Now I can add the real libs.

**Comment by jakub-bao** [comment]
Next step will be:

Add the following libraries to the project
```
    "@dhis2/ui-core": "^4.1.1",
    "@dhis2/ui-widgets": "^2.0.5",
    "@dhis2/app-runtime": "^2.0.4",
    "@dhis2/d2-i18n": "^1.0.6",
    "d2": "^31.8.0",
    "styled-jsx": "^3.2.4",
```

**Comment by jakub-bao** [comment]
Importing the REACT libs into Angular is a bit trickier then I thought:

![image](https://user-images.githubusercontent.com/47790868/73103589-678b9580-3ec2-11ea-8438-dcc19bd600e2.png)

`exports` & `require` is not defined.
I'll have to run the libraries through `babel` or `webpack` to deal with that.

**Comment by jakub-bao** [comment]
I might need to go the route that I'll just create a blank `react` project and add the `2.33 header bar`
and then take all the compiled `js` code and copy paste it.

It might be the fastest way.

**Comment by jakub-bao** [comment]
I have an absolute minimalistic deployment of 2.33 header bar:

![image](https://user-images.githubusercontent.com/47790868/73194034-84f67480-40f9-11ea-9f6b-c6ed00f4c150.png)


Will go from there...

**Comment by jakub-bao** [comment]
everything fits into one file

```
import React from 'react';
import ReactDOM from 'react-dom';

import {HeaderBar} from '@dhis2/ui-widgets';
import {Provider} from '@dhis2/app-runtime';
import {init, config} from 'd2';

const baseUrl = 'https://newrelease.datim.org/';

config.baseUrl = baseUrl + 'api';
config.i18n.sources.add('i18n.txt');

function HeaderbarPackage(){
    return <Provider config={{baseUrl: baseUrl, apiVersion: '30'}}>
        <HeaderBar/>
    </Provider>
}

init().then(()=>{
    ReactDOM.render(<HeaderbarPackage/>, document.getElementById('header-bar'));
});

```

**Comment by jakub-bao** [comment]
OK, it's working in prod settings with the app as well.
Just needs some polishing:

![image](https://user-images.githubusercontent.com/47790868/73202655-7adc7200-4109-11ea-8278-ce226f852b8c.png)

**Comment by jakub-bao** [comment]
HM, unfortunately the app is having issues displaying data with the 2.33 header bar:
![image](https://user-images.githubusercontent.com/47790868/73203396-f7bc1b80-410a-11ea-90cf-2bdc9f00ad05.png)

**Comment by jakub-bao** [comment]
It was due to missing JS files.

However, now this SQL view issue:

![image](https://user-images.githubusercontent.com/47790868/73203499-2afeaa80-410b-11ea-8453-1b8c885d9a88.png)

**Comment by jakub-bao** [comment]
Everything working now except the user initials being out of place..

![image](https://user-images.githubusercontent.com/47790868/73203799-c5f78480-410b-11ea-956b-ab88bcb08879.png)

**Comment by jakub-bao** [comment]
initials being out of place resolved..

**Comment by benguaraldi** [comment]
Complete?  I think so.  Closing.
