### ISSUE TITLE
Allow for filtering of dedupes by organisation unit branch

### ISSUE THREAD

**Issue by jason-p-pickering** [pepfar-datim/datim-dedupe#112]
Add a new paramater to the backend to filter all dedupes within a single branch of the organisation unit hierarchy. 

Implement a tree picker in the UI to allow for users to choose a single organisation unit, and thus filter all dedupes within that branch.

**Comment by jakub-bao** [comment]
Hi @jason-p-pickering No problem on this one. Can you go ahead with implementing the backend first and then let me know I'll add the UI?

**Comment by benguaraldi** [comment]
Duplicate of #119.
