### ISSUE TITLE
Test Local DB with Worst Case Scenario

### ISSUE THREAD

**Issue by hardingt** [pepfar-datim/datim-dedupe#117]
Steps to allow this query to work:

1. Enable dedupe for Targets FY17 here
https://test.datim.org/dhis-web-datastore/index.html#/edit/dedupe/periodSettings
![image](https://user-images.githubusercontent.com/11567315/74471284-f52d2600-4e6d-11ea-9a5c-a0c8110097ed.png)

Run the following, you should get around 48k records:
https://test.datim.org/api/sqlViews/wzpSd6j89wc/data?cacheBuster=1234&paging=false&var=ou:PqlFzhuPcF1&var=pe:2017Oct&var=rs:true&var=ps:50000&var=pg:1&var=dt:TARGETS&var=ty:PURE&var=ag:NONE&var=dg:NONE

This is by far the worst case we've had for dedupes, and it seems to be an anomaly (ie, the total numbers are going down year over year).

At minimum we'd be able to sort by facility name, sort by tech area, filter by Agency, Filter by Mechanism, filter by facility etc... faster than the SQL function (which requires re-querying every time we change the page or filter) and only display maybe a max of 100 or 200 to the screen at once.

Thankfully, the users are very much accustomed to waiting for that first query to finish, so we have some leeway with the timing to populate the local db.

Note: Some servers have gzip transit compression turned on, some do not. I am working with Ops to get it turned on for all servers.

**Comment by jakub-bao** [comment]
Sure will do. No prob.
@benguaraldi LOE should be 2-3 days.

**Comment by jakub-bao** [comment]
@hardingt Bingo!

Wow, I can't believe but having all the dedupes in browser memory and filtering & sorting there is just fine. 
Big respect to folks from Google though :)

FYI, these are my tests:

I wrote a little program which stores all the 33MB of dedupes in browser memory.
And then it can sort & filter by any column.
Filtering is 20ms and sorting 200ms. Just wow.

![image](https://user-images.githubusercontent.com/47790868/77556893-73c6ab80-6e8f-11ea-8a3f-31459fa62602.png)

Code here
```
console.log('DB Test Script');

function stripRows(data){
    return data.listGrid.rows;
}

function transformData(dedupeArray){
    return dedupeArray.map(array=>{return {
        ou: array[0],
        dataElement: array[1],
        disaggregation: array[2],
        agency: array[3],
        mechanism: array[4],
        partner: array[5],
        value: array[6],
        duplicateStatus: array[7],
    }});
}

fetch('/data.json')
    .then(data=>data.json())
    .then(stripRows)
    .then(transformData)
    .then(data=>{
        console.log(data);
        runAllTests(data);
});

let testNr = 1;

function testTask(f){
    console.log('\n\n')
    console.log(`Test no ${testNr++}`);
    console.time('execution time');
    let res = f();
    console.log(res);
    console.timeEnd('execution time');
}

function findDedupesBy(data, field, value){
    console.log(`find dedupes by ${field}='${value}'`);
    return data.filter(o=>o[field]===value);
}

function sortDedupes(data, field, order){
    console.log(`sorting dedupes by ${field} in ${order} order`);
    function sortFunction(a,b){
        if (order==='asc') return a[field]>b[field]?-1:1;
        if (order==='desc') return a[field]>b[field]?-1:1;
        throw 'cannot recognize sort order';
    }
    return data.sort(sortFunction);
}

function runAllTests(data){
    testTask(()=>findDedupesBy(data,'ou', 'Eja Memorial Hospital'));
    testTask(()=>findDedupesBy(data,'dataElement', 'TX_CURR (N, DSD) TARGET: Receiving ART'));
    testTask(()=>sortDedupes(data,'ou','desc'));
    testTask(()=>sortDedupes(data,'dataElement','desc'));
}
```

**Comment by benguaraldi** [comment]
Wow!  That's fantastic news, @jakub-bao!

**Comment by jakub-bao** [comment]
@hardingt I'm glad you thought of this. It can make the app significantly(!) more responsive.

@hardingt @benguaraldi FYI, in this used case it'll take 40s to fetch all the dedupes from the API.

**Comment by hardingt** [comment]
@jakub-bao yup! find the jeopardy theme song and play it for the users :D 

This is fantastic news. Thank you @jakub-bao , This will make the future dedupe app a lot more speed and usability

**Comment by benguaraldi** [comment]
@jakub-bao Does it make sense to store the data after loading it the first time so that the next time the user comes to the app, it's already there?

**Comment by hardingt** [comment]
@benguaraldi At this point no.
every visit should be considered new and should fetch all dedupes again.

**Comment by benguaraldi** [comment]
Sounds good.  Thanks!

**Comment by jakub-bao** [comment]
@benguaraldi We could do that IF:

1) We have a reliable way to detect if there have been any changes in dedupes since last visit.

2) Chrome will let us to store the 30MB of data in browser's local storage.

ad 2) It should be possible. There was a 5MB limit but supposedly there should be a solution to this: https://developer.chrome.com/apps/offline_storage

I'd go with a full refresh for now and then try to implement this in step two.

**Comment by benguaraldi** [comment]
Sounds good—thanks!

**Comment by jakub-bao** [comment]
@hardingt Hi Tim, there one problem with doing all filtering and sorting on the front-end.

The current query to view dedupes has three required parameters: `ou`, `workflow` & `period`.
I can't get all dedupes in 1 query. I'd need to make `28*2*number_of_reporting_periods` queries to get all the data in the front-end.

Can we create a simple query to get ALL dedupes for ALL ous, periods & workflows?

cc @benguaraldi @jason-p-pickering

**Comment by hardingt** [comment]
@jakub-bao there is a pagesize that can be set to 100,000 `&var=ps:100000`

**Comment by jakub-bao** [comment]
@hardingt Well the problem is that you have to specify `ou`, `worflow` & `period` and it doesn't accept `Global`.
That is 28 * 2 * number_of_periods queries.

**Comment by hardingt** [comment]
@jakub-bao I get you! That is totally fine
The users here are InterAgency, meaning they have to be an OU. We wouldn't want Angola IA users to see Botswana's Dedupes

**Comment by jakub-bao** [comment]
Oh, yeah I forgot. I got confused by this:
The current app, although being a Rwanda Inter-Agency user presents me with a drop-down with all OUs.

![image](https://user-images.githubusercontent.com/47790868/78259824-2ff52700-74cb-11ea-878d-2b3d64334597.png)

**Comment by jakub-bao** [comment]
@hardingt So I can count on the Dedupe app users will be mostly Inter-Agency users assigned to a single OU?

How about Global / super-admin ?

**Comment by hardingt** [comment]
All users will be IA for the actual work of deduping and should ONLY see their one OU
SUs that will need access to the app will need a way to select any OU. BUT, the SUs that will be in there poking around will only need one OU at a time.

Side issue:
I am confused that the app is showing all countries on your dev box, it should not be doing that. @jason-p-pickering or @tomzemp should IA users see an OU dropdown?

**Comment by benguaraldi** [comment]
@hardingt Would it work for the app to check the user's organisation unit via `api/me.json`.  If it's not Global, use that OU.  If it is Global, give them a dropdown?

What should be in the dropdown?  Countries, or level 3 org units?

**Comment by hardingt** [comment]
@tomzemp correct me if I'm wrong here, but I believe the design docs have a section for selecting the OU? Wasn't that like a stretch goal?

@benguaraldi I think we can add a drop down for all users above level 3, In the drop down will be Operating Units (Level 3) As well as a tree that is informed by the dropdown. That would be the simplest solution I can see.

Super user Selects Angola:
![image](https://user-images.githubusercontent.com/11567315/78561319-845b1800-77e5-11ea-804b-de6c81e37c06.png)

IA User is assigned to Angola:
![image](https://user-images.githubusercontent.com/11567315/78561350-8fae4380-77e5-11ea-805a-3907c5256f5c.png)

**Comment by benguaraldi** [comment]
@jakub-bao, I talked with @hardingt, and we agree that [his comment](#issuecomment-609781365) makes sense, but shouldn't be in the MVP version of the react Dedupe app.  I'll split it out into another ticket, which we can tackle when the MVP react Dedupe is complete.

**Comment by benguaraldi** [comment]
I've moved the operating unit tree to #119.  Note that it is not MVP.

**Comment by benguaraldi** [comment]
@hardingt @jakub-bao This ticket can be closed, right?

**Comment by hardingt** [comment]
Yup!
