### ISSUE TITLE
Displaying resolved Dedupes

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-dedupe#121]
Now I finally understand how the dedupes logic works.
"Resolving a dedupe" means creating a new data entry record for `Deduplication agency` `mechanism # 000000` with a negative number.

Example:
![image](https://user-images.githubusercontent.com/47790868/78825684-67257580-79ae-11ea-8978-618a9b029bab.png)

Since this is new I'll have to add this used case to the new app's rendering of dedupes.

**Comment by jason-p-pickering** [comment]
@jakub-bao that is correct. There are some more business rules there, and if anything is not clear, let me know and we can talk through it.

**Comment by jakub-bao** [comment]
@jason-p-pickering I think I get it for now. But thanks. Might have some questions later one.

Notes to self:

I wrote a script which can successfully detect `resolution method` `max,sum, custom`.
Add this tomorrow to the component view and add to an automated test.
Current dataset for Nigeria has data for `max` dedupe.
Add tests for `sum` & `custom`:

![image](https://user-images.githubusercontent.com/47790868/78939146-95c05080-7a81-11ea-8c09-e19cab36bbbe.png)

**Comment by benguaraldi** [comment]
@jakub-bao I'm closing this, as I think it's complete.  Please reopen if I'm wrong.
