### ISSUE TITLE
Constrain periods for given OU

### ISSUE THREAD

**Issue by tomzemp** [pepfar-datim/datim-dedupe#122]
Hi @jakub-bao:

For the new app, it would be desirable to build in the functionality to constrain periods for a given OU, using the datastore. (E.g. specificy that for Bostwana `2020Oct` should only be accessible between `2020-01-01` and `2020-02-01` even if for all other countries it's normally acessible between `2020-01-01` and `2020-04-01`( 

We started on this in the old app (https://github.com/pepfar-datim/Global/issues/3163) but Jason P thought that it would cause problems for his back end script, so we didn't pursue further. I think some of those problems (e.g. dedupe report) should no longer be pertinent, and the other problems might not have actually been problems, but Jason never had time to test properly.
After talking with Tim, it seems more sensible to just make sure this requirement gets incorporated into the new app.

I initially implemented in the format that Jason had recommended (https://github.com/pepfar-datim/datim-dedupe/issues/64#issue-242592105), but you could probably structure it some otherway if you prefer.

Let me know if you want to discuss anything.
FYI @hardingt @benguaraldi

**Comment by benguaraldi** [comment]
@jakub-bao This isn't MVP for the new app, but whenever you can incorporate it would be great.  Thanks!

**Comment by benguaraldi** [comment]
Closing in favor of #64.
