### ISSUE TITLE
Download CSV not working

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-dedupe#123]
implementation details from https://github.com/pepfar-datim/Global/issues/6640 here

**Comment by jakub-bao** [comment]
steps to reproduce:
1. dev-jakub
2. dedupe app
3. Rwanda / Results / April 2020
4. Agency: USAID
5. Technical Area: not selected
6. F12

- query generated inside the app will generate this url `https://dev-jakub.datim.org/api/sqlViews/wzpSd6j89wc/data?cacheBuster=1593533712567&paging=false&var=ou:XtxUYCsDWrR&var=pe:2020Q2&var=rs:false&var=ps:50&var=pg:1&var=dt:RESULTS&var=ty:PURE&var=ag:NLV6dy7BE2O&var=dg:NONE`

- query generated for CSV download will generate wrong url  `https://dev-jakub.datim.org/api/sqlViews/wzpSd6j89wc/data.csv?var=ou:XtxUYCsDWrR&var=pe:2020Q2&var=rs:false&var=ps:50&var=pg:1&var=dt:RESULTS&var=ty:PURE&var=ag:2&var=dg:&cacheBuster=1593533712841`

agency is wrong and dg is wrong

**Comment by benguaraldi** [comment]
OBE with new app. Closing.
