### ISSUE TITLE
Add Status & Resolve Button

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-dedupe#132]
src: https://whimsical.com/filters-unresolved-work-G7MkaNADDwtuVer4v8sdWb

**Comment by benguaraldi** [comment]
Per https://github.com/pepfar-datim/Global/issues/5229#issuecomment-728330592:

Change the statuses to:

1.

Resolved on server
[Unresolve]

2.

Ready to resolve
[Resolve]

3.

Errors

4.

Ready to edit
