### ISSUE TITLE
Make Dedupe Type required

### ISSUE THREAD

**Issue by benguaraldi** [pepfar-datim/datim-dedupe#135]
I believe that a selection of Dedupe Type is required.  Please add an asterisk.

![Screen Shot 2020-11-16 at 4 18 40 PM](https://user-images.githubusercontent.com/852673/99313566-c5141880-282d-11eb-896a-b54762874c43.png)

**Comment by jakub-bao** [comment]
@benguaraldi should be fixed. can u check on `ben.datim` and close?

**Comment by benguaraldi** [comment]
Fixed!  Thanks, @jakub-bao!
