### ISSUE TITLE
User cannot deselect Agency or Technical Area filter options, once selected

### ISSUE THREAD

**Issue by DavidNesbitt2020** [pepfar-datim/datim-dedupe#140]
Related to first pass testing on #139 

Issue: As the user, I may search for a Technical Area in the v2 Dedupe app. However, I do not have the option to "deselect" a Technical Area.  I would have to navigate away from the app, then reload the app, in order to clear the filter.

![image](https://user-images.githubusercontent.com/73136568/100910056-73a99180-349b-11eb-8a63-d3a5cefb7bee.png)

![image](https://user-images.githubusercontent.com/73136568/100909525-db131180-349a-11eb-9401-973b99c0427c.png)

Possible solution? Add a field for "Any Technical Area" like the previous app:
*I also recommend changing it from "Any" to "All" (if easy to change).

![image](https://user-images.githubusercontent.com/73136568/100909761-17df0880-349b-11eb-9236-f434d8c087b3.png)

@jakub-bao

**Comment by DavidNesbitt2020** [comment]
Same for Agency filter:

![image](https://user-images.githubusercontent.com/73136568/100910269-bec3a480-349b-11eb-8d34-cfe55b499608.png)

**Comment by benguaraldi** [comment]
I agree that this is a problem.  I think it's MVP, unless it's very high LOE.  @jakub-bao, please let me know.

**Comment by benguaraldi** [comment]
This works for me as well:
> All technical areas

**Comment by jason-p-pickering** [comment]
If we are using client side filtering it probably makes more sense to have a mulitselect combo which the user can add to or remove items from. With the current server side filtering approach, only a single technical area is supported however.

**Comment by benguaraldi** [comment]
For MVP, we are doing server side filtering. We can look into more complex filtering later, though. I'll make a ticket for that.

**Comment by benguaraldi** [comment]
@jakub-bao Close!  Could we change the word `Unspecified` to `All Agencies` and `All Technical Areas`?

I like the italics, so if it's possible to keep those, please do.

**Comment by benguaraldi** [comment]
@jakub-bao I have a comment on this that doesn't look like it got incorporated:
https://github.com/pepfar-datim/datim-dedupe/issues/140#issuecomment-747581732

So this isn't done yet.

**Comment by benguaraldi** [comment]
Achievement unlocked!  Closing.

**Comment by DavidNesbitt2020** [comment]
yay!

![image](https://user-images.githubusercontent.com/73136568/104318840-f61b6d00-54ad-11eb-9b3f-4530a0801bf4.png)
![image](https://user-images.githubusercontent.com/73136568/104318868-029fc580-54ae-11eb-9cda-0404d65873cc.png)
