### ISSUE TITLE
Initial loading selection prompt

### ISSUE THREAD

**Issue by DavidNesbitt2020** [pepfar-datim/datim-dedupe#141]
Related to #139 

After the v2 dedupe app loads, an arrow appears telling the user to "Please select an Operating Unit".

Can this feature be expanded to include the other required fields (Data Type and Period)?

![image](https://user-images.githubusercontent.com/73136568/100911647-80c78000-349d-11eb-9965-64af6586db1c.png)

**Comment by DavidNesbitt2020** [comment]
Example: 
![image](https://user-images.githubusercontent.com/73136568/100911972-ea478e80-349d-11eb-882a-51d77cf95308.png)

**Comment by benguaraldi** [comment]
I think it might be better to just have them all in one phrase, like:
> Please select an Operating Unit, Data Type, and Period, and then click Search Dedupes

**Comment by benguaraldi** [comment]
@jakub-bao Please do this, but just by changing the initial phrase as indicated in my comment above:
https://github.com/pepfar-datim/datim-dedupe/issues/141#issuecomment-737505349

**Comment by jakub-bao** [comment]
@DavidNesbitt2020 fixed. can u please confirm and close?

**Comment by benguaraldi** [comment]
Fixed!  Thanks, @jakub-bao!
