### ISSUE TITLE
Descriptive column headers

### ISSUE THREAD

**Issue by DavidNesbitt2020** [pepfar-datim/datim-dedupe#142]
The new Dedupe v2 app (left side-red) does not include the column headers for Agency, Partner, Mechanism, and Value, found in the first app (right side-green).

I believe this feature should be continued in the new app because it distinguishes between those key data points for users. Especially between mechanism and value numbers. Many dedupe app users have reported spending many days and nights working through hundreds of dedupes for their OUs and being able to distinguish between these columns is important.

![image](https://user-images.githubusercontent.com/73136568/100924794-14557c80-34af-11eb-9dc8-70289d5e6bfc.png)

@benguaraldi and/or @ssearle-bao - This may be debatable though, so please let us know if you have any opinions.

**Comment by DavidNesbitt2020** [comment]
Related to #139

**Comment by benguaraldi** [comment]
@DavidNesbitt2020 We are aware of this, and think it's worth doing, but not MVP.

@ssearle-bao, let me know if you disagree.

**Comment by ssearle-bao** [comment]
@benguaraldi , I just chatted with @DavidNesbitt2020 and we both think this is pretty confusing - it's difficult to tell what is the value to be deduped versus the mech number, etc. 

Is the level of effort extraordinary to include this in the MVP? If so, I can be talked out of it, but I do think this is of reasonable importance.

**Comment by benguaraldi** [comment]
It does turn out to be tricky, as it's a table within a table, basically.

How long can we delay the MVP to include this?  I don't think we'd be looking at more than two weeks.

**Comment by ssearle-bao** [comment]
OK. @benguaraldi and I chatted and we think we should get everything done for the MVP prior to accomplishing this. If we have some leeway once those core features is accomplished, @DavidNesbitt2020 and I think this is important and should be prioritized.

**Comment by benguaraldi** [comment]
(Regardless, this should be one of the first things post-MVP.)

**Comment by jakub-bao** [comment]
@DavidNesbitt2020 fixed. can you please confirm and close?

**Comment by DavidNesbitt2020** [comment]
I can confirm that the headers are there now, but the alignment is a little wonky. Is that an adjustment that could be easily made @jakub-bao?

![image](https://user-images.githubusercontent.com/73136568/102532212-a2199600-4071-11eb-8ea7-eba995cc3902.png)

**Comment by benguaraldi** [comment]
@DavidNesbitt2020 My guess is that's hard, but let's tackle it as part of #153.
