### ISSUE TITLE
Flip row background colors

### ISSUE THREAD

**Issue by benguaraldi** [pepfar-datim/datim-dedupe#144]
Right now, the row background colors blend in a weird way.  This could be solved by flipping the internal row colors.

It looks like this presently:
![Screen Shot 2020-11-30 at 3 05 28 PM](https://user-images.githubusercontent.com/852673/100934783-45d54480-34bd-11eb-9257-6c232b611e59.png)

Please fix by changing the row colors as follows:
- row 1 (with 16848, 30010): keep the same
- row 2 (with 16850, 30020): keep the same
- row 3 (with 14169, 20010): make the color of row 4 (with 14302, 20020)
- row 4 (with 14302, 20020): make the color of row 3 (with 14169, 20010)

This is not MVP.

**Comment by jakub-bao** [comment]
done
