### ISSUE TITLE
Download all dedupes as CSV

### ISSUE THREAD

**Issue by DavidNesbitt2020** [pepfar-datim/datim-dedupe#146]
We know from https://github.com/pepfar-datim/Global/issues/6640 that users download CSV files of their duplicates.

In the current v2 dedupe app, I do not see a way in which a user could download a CSV of their OUs duplications.

Current Deduplication app:
![image](https://user-images.githubusercontent.com/73136568/101173485-9ad59f80-3610-11eb-9464-fd3b284dcd97.png)

Dedupe v2 App being tested in https://github.com/pepfar-datim/datim-dedupe/issues/139:
![image](https://user-images.githubusercontent.com/73136568/101173587-bd67b880-3610-11eb-8cb1-43f268a0a148.png)

@benguaraldi for MVP assessment
FYI @ssearle-bao

**Comment by benguaraldi** [comment]
@ssearle-bao I think we probably need this for MVP.  Do you agree?

**Comment by ssearle-bao** [comment]
Yes. Agree.

**Comment by jakub-bao** [comment]
done. to be reviewed @ ben.datim

**Comment by DavidNesbitt2020** [comment]
I successfully pulled a csv using the feature at the bottom of the new app. 

[datim-dedupe-app test csv.xlsx](https://github.com/pepfar-datim/datim-dedupe/files/5711662/datim-dedupe-app.test.csv.xlsx)
(converted to xlsx for GH though)

**Comment by benguaraldi** [comment]
@DavidNesbitt2020 Cool!  Does the CSV look right?

**Comment by DavidNesbitt2020** [comment]
@benguaraldi yep! just like DATIM Prod (right side):

![image](https://user-images.githubusercontent.com/73136568/102534200-5f0cf200-4074-11eb-88e8-7f6451618422.png)

**Comment by benguaraldi** [comment]
Perfect!  Closing.
