### ISSUE TITLE
Status Column Color Scheme

### ISSUE THREAD

**Issue by DavidNesbitt2020** [pepfar-datim/datim-dedupe#147]
Related to #139 

Not to sound too much like an old man, but the color scheme and font in the Dedupe v2 apps Status column are really dark.

![image](https://user-images.githubusercontent.com/73136568/101176819-06217080-3615-11eb-9cf3-bb868bbc25f9.png)

Is there a quick and easy enhancement to update them to be more contrasted and distinct?

Possible ideas for change(s):
- Change font color to white and bold it?
- Make font larger size?
- Change the background status color to something brighter?

@benguaraldi for MVP assessment
____________________________________

Current Dedupe app color scheme example:

![image](https://user-images.githubusercontent.com/73136568/101177210-8942c680-3615-11eb-9738-dd35b5d8647d.png)

**Comment by benguaraldi** [comment]
I think they are bold, but I believe the font is supposed to be white.  @jakub-bao?

**Comment by jakub-bao** [comment]
@DavidNesbitt2020 Hi, this should be fixed. Can you please confirm and close?

**Comment by DavidNesbitt2020** [comment]
Yes, confirmed in ben.datim. Thanks!

![image](https://user-images.githubusercontent.com/73136568/102534368-a2676080-4074-11eb-979d-9a203e651505.png)

![image](https://user-images.githubusercontent.com/73136568/102534399-b01ce600-4074-11eb-868f-0ebea48ec74f.png)
