### ISSUE TITLE
Minor Bug: OU Selection List gets "cut-off" after a while

### ISSUE THREAD

**Issue by DavidNesbitt2020** [pepfar-datim/datim-dedupe#148]
Related to #139 

After navigating around the Dedupe v2 app with a superuser account, I've noticed the OU selection list eventually cuts off at the top. 

This issue happens in Pivots app and the current workaround is to zoom in or out of the window. However, zooming does not work in this case.

![image](https://user-images.githubusercontent.com/73136568/101202264-09c5ef00-3637-11eb-9fda-d973b3e00c57.png)

Since this occurs with a Superuser account, where all OUs are available, this may not have any real implications for users since none should be accessing the Dedupe app with the ability to see beyond their own OU.

@benguaraldi @jakub-bao - Please review and close this ticket if you agree.

**Comment by benguaraldi** [comment]
@DavidNesbitt2020 Thanks!  Let's leave this open.  But it's definitely not MVP.

**Comment by benguaraldi** [comment]
Works for me, but I never noticed the original problem.  @DavidNesbitt2020, could you test?

**Comment by DavidNesbitt2020** [comment]
I can't replicate that minor bug anymore - which is great!  Thanks :)

![image](https://user-images.githubusercontent.com/73136568/103773572-43ed2c80-4ff9-11eb-85d8-a0847bdeed45.png)
