### ISSUE TITLE
correctly read timezone from date format in REACT dedupe app

### ISSUE THREAD

**Issue by hardingt** [pepfar-datim/datim-dedupe#150]
Current dedupe app complains about timezone offsets:

![image](https://user-images.githubusercontent.com/11567315/101633291-08107880-39f5-11eb-8438-4dba4b570050.png)

https://www.ionos.com/digitalguide/websites/web-development/iso-8601/#:~:text=According%20to%20the%20basic%20format,%3A%2012%3A07%3A22.

If I change the timezone offset to 00:00 it works again.

cc @benguaraldi

**Comment by benguaraldi** [comment]
I think #131 covers this, right?

**Comment by hardingt** [comment]
yes @benguaraldi I am happy I am not the first to discover this :D
