### ISSUE TITLE
Align column spacing in dedupe list

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-dedupe#153]
![image](https://user-images.githubusercontent.com/47790868/102526496-bb1e4900-4069-11eb-973a-e122998cbfff.png)

cc @benguaraldi

**Comment by benguaraldi** [comment]
I would love it if this got fixed!

**Comment by benguaraldi** [comment]
@DavidNesbitt2020 wrote on https://github.com/pepfar-datim/datim-dedupe/issues/142#issuecomment-747641090:
> I can confirm that the headers are there now, but the alignment is a little wonky. Is that an adjustment that could be easily made @jakub-bao?

![image](https://user-images.githubusercontent.com/73136568/102532212-a2199600-4071-11eb-8ea7-eba995cc3902.png)

**Comment by benguaraldi** [comment]
This is complete.
