### ISSUE TITLE
"Unset Method" button

### ISSUE THREAD

**Issue by benguaraldi** [pepfar-datim/datim-dedupe#156]
Below the "Set to Maximum" and "Set to Sum" buttons, please add an "Unset Method" button.

This button should change the Resolution so that none of the options are selected. 

If the dedupe has already been resolved, then it should change the Status to a red box that says "Ready to unresolve" with a button that says "UNRESOLVE".

If the dedupe has not been resolved, then it should change the Status to "Unresolved".

@ssearle-bao to decide whether this is MVP.

**Comment by ssearle-bao** [comment]
What is the current behavior here? What recourse does the use have if they select a method on accident for resolving and want to change it?

**Comment by DavidNesbitt2020** [comment]
Right now, as built, the user it stuck with whatever method they chose and would have to exit the app to "deselect".

**Comment by ssearle-bao** [comment]
Hm. That's pretty annoying. I know that this feature wasn't part of the previous reqs so it makes sense that @benguaraldi doesn't consider it MVP but it does seem pretty important.

@benguaraldi , I assume LOE for this is fairly high?

**Comment by benguaraldi** [comment]
@jakub-bao pointed out that as a result of this, we need to change the button from `Resolve`.  We suggest `Execute`.

**Comment by DavidNesbitt2020** [comment]
Which button? This one?
![image](https://user-images.githubusercontent.com/73136568/103812798-11f5bd80-502d-11eb-81ab-34a6e37072f1.png)

**Comment by benguaraldi** [comment]
@DavidNesbitt2020 Yes, that one.  If we leave it as `Resolve`, then it will also be saving `Ready to unresolve` items to the server...or it won't.  Either will be confusing.

**Comment by benguaraldi** [comment]
Looks good!  Thanks, @jakub-bao!
