### ISSUE TITLE
Unable to enter the number 0 alone in the Custom Value text box

### ISSUE THREAD

**Issue by benguaraldi** [pepfar-datim/datim-dedupe#160]
When I try to write the number 0 in the Custom Value text box, nothing appears.

0 should appear, but be marked as an invalid value.

**Comment by jason-p-pickering** [comment]
I don't think zero should ever be allowed as a custom value. The only case
where this would be possible would be when you have two or more zeros as
duplicate components, which should not be flagged as a dupe to begin with.

**Comment by benguaraldi** [comment]
@jason-p-pickering I totally agree!  What I'm asking for here is that when a 0 is typed, it appears in the text box as an invalid entry.  Right now, it just acts as if no 0 was types, which is weird UI.

**Comment by jakub-bao** [comment]
@benguaraldi fixed. will let you know when i deploy all the changes for testing (probably tomorrow).

**Comment by benguaraldi** [comment]
Works for me.  Thanks!
