### ISSUE TITLE
Combine all required fields into one directive

### ISSUE THREAD

**Issue by Markionium** [pepfar-datim/datim-dedupe#17]
To create a bit more cleaner interface in the controller we could combine all the required fields in one directive instead of several and offload some controller logic to the directive.

**Comment by jason-p-pickering** [comment]
Could you provide more information here?

**Comment by Markionium** [comment]
This is a technical thing only basically.

Angular works with directives which are basically grouping ui functionality. Currently all the filter dropdowns are controlled by their own directive and the app has to keep track of each of them.

It would be nicer if these are combined into a filter directive of a sort where the app would then just get a notification that the filters have been updated and receive the values instead of having to keep track of them separately.

**Comment by benguaraldi** [comment]
OBE.
