### ISSUE TITLE
Dedupe column order correct?

### ISSUE THREAD

**Issue by benguaraldi** [pepfar-datim/datim-dedupe#173]
@jakub-bao pointed out that it might make more sense to have the column order different in the app.

Right now it looks like this:
![Screen Shot 2021-01-13 at 2 09 03 PM](https://user-images.githubusercontent.com/852673/104498477-bc2f9100-55a9-11eb-9c20-8a2be890551d.png)

Should it instead be Mech, Agency, Partner, Value?

@ssearle-bao to decide, and maybe input from @DavidNesbitt2020 or @hardingt.

**Comment by DavidNesbitt2020** [comment]
FWIW, I like this recommendation. I think separating columns with number values would make deciphering the table mush easier.

**Comment by ssearle-bao** [comment]
Great. Let's do it.

**Comment by benguaraldi** [comment]
Thanks all!  Let us know when it's ready, @jakub-bao!

**Comment by benguaraldi** [comment]
Looks good!
