### ISSUE TITLE
Error on network connection loss

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-dedupe#176]
Since it's possible that user might do a bunch of edits before commiting them to the server.
It might be good to warn the user if their network connection gets dropped.
A red error message will pop up. It will disappear when they get back online. (Facebook, YouTube etc. does the same)

cc @benguaraldi

**Comment by benguaraldi** [comment]
Sure, that seems like a good idea.  How often will you poll?  And how?

**Comment by benguaraldi** [comment]
Looks good!  One thing—it seems like the "you're online" should cancel the "you're offline" warning if possible.  (Is it?)

**Comment by benguaraldi** [comment]
Looks great!  Closing.
