### ISSUE TITLE
Partner and Agency users can access Data Deduplication without data deduplication role

### ISSUE THREAD

**Issue by srihtanguturi** [pepfar-datim/datim-dedupe#189]
@benguaraldi 
Environment: nr.testing.datim.org
User: partnertester1 and agencytester1

Partner and Agency users can see and navigate to the Data Dedupe app in v2.0.0 even though they don't have a Data dedupe role.

**Partnertester1**:
Available apps - User doesn't have access to Data Deduplication 1.5.6 app whereas the user can see Data Deduplication 2.0.0 app.
<img src="https://user-images.githubusercontent.com/24919495/105766195-6f43a700-5f27-11eb-9ed2-2e70ab41d598.png" width="300" height="300">
Partner user's roles
![image](https://user-images.githubusercontent.com/24919495/105763276-9ac49280-5f23-11eb-9b90-7d1bbe20b6de.png)

**Agencytester1**:
<img src="https://user-images.githubusercontent.com/24919495/105766689-0d377180-5f28-11eb-909e-2bfd160df432.png" width="300" height="300">

Agency user's roles
![image](https://user-images.githubusercontent.com/24919495/105763990-62718400-5f24-11eb-8571-c87c3f737a42.png)

**Comment by benguaraldi** [comment]
@srihtanguturi This is expected behavior—when installing dev apps, we allow all users to see them.  The production app will not be visible to all users.

Closing.
