### ISSUE TITLE
Crosswalk dedupes: Search by Technical Area is not working

### ISSUE THREAD

**Issue by srihtanguturi** [pepfar-datim/datim-dedupe#193]
@benguaraldi
Environment: nr.testing.datim.org
User: interagencytester1

Filtering crosswalk dedupes by Technical Area doesn't filter the dedupe records instead all the dedupes were displayed.

Steps:
1. Login as interagencytester1 user and navigate to Dedupe 2.0.0
2. Select the below search options
a. Dedupe type: Crosswalk dedupes
b. OU: Botswana
c. Data Type: MER Results
d. Period: Oct - Dec 2020
e. Technical Area: CARE_SITE (_Any TA other than the dedupes that were already there_)
3. Click on Search dedupes and verify that the dedupe records are filtered to display only the matching dedupes.

![image](https://user-images.githubusercontent.com/24919495/106494714-bfbb8700-6488-11eb-94b7-8c8cfa3ad49a.png)

**Comment by benguaraldi** [comment]
I believe this is working now.  @srihtanguturi, could you retest?

Note that this may have been a problem in 1.5.6, so yay for us fixing it in the new version!

**Comment by srihtanguturi** [comment]
Retested and working as expected
