### ISSUE TITLE
Crosswalk dedupes: DSD value is not matching with Pure dedupes sum value

### ISSUE THREAD

**Issue by srihtanguturi** [pepfar-datim/datim-dedupe#194]
@benguaraldi 
Environment: nr.testing.datim.org
User: interagencytester1

The sum of Pure dedupe for a Data Element is not matching with DSD value on Crosswalk dedupes.  Crosswalk dedupes is adding the values up to 2 mechanisms and the sum is displayed under DSD Value whereas when 3 or more mechanisms are displayed in pure dedupe then the sum of DSD value is not matching with pure dedupes.

Scenario 1: 
1. Create crosswalk dedupe with 2 mechanisms on Pure dedupe page
2. The sum of all mechanisms values on a pure dedupe shall be summed and displayed on Crosswalk dedupe as DSD value

Scenario 2: 
1. Create crosswalk dedupe with 3 or more mechanisms on Pure dedupe page
2. The sum of all mechanisms values on a pure dedupe shall be summed and displayed on Crosswalk dedupe as DSD value
3. The sum on Pure dedupes did not match with DSD value on Crosswalk dedupes page.

**Pure Dedupes page:**
![image](https://user-images.githubusercontent.com/24919495/106497612-46259800-648c-11eb-8b78-7a6ce50a0eb0.png)

**Crosswalk Dedupes page:**
![image](https://user-images.githubusercontent.com/24919495/106498648-93eed000-648d-11eb-8034-9b5b325770bc.png)

**Comment by benguaraldi** [comment]
This scenario is a little more complicated than what @srihtanguturi wrote.  It only arises when a data value is changed after the pure dedupe is resolved.  The pure dedupe is showing correctly as unresolved, as the incorrect value will be deleted by script.

However, the crosswalk dedupe was showing that the pure dedupe had been resolved and therefore allowing the crosswalk dedupe to be resolved.

Anyhow, this should work now.  Please retest, @srihtanguturi.

**Comment by srihtanguturi** [comment]
Retested and working as expected.
