### ISSUE TITLE
Crosswalk Dedupes: Unresolved Pure dedupes are displayed as editable on Crosswalk dedupes instead of with status "Unresolvable crosswalk"

### ISSUE THREAD

**Issue by srihtanguturi** [pepfar-datim/datim-dedupe#195]
@benguaraldi 
Environment: nr.testing.datim.org
User: interagencytester1

Able to resolve Crosswalk dedupe before Pure dedupe is resolved. But if pure dedupe was resolved once and reverted back then crosswalk dedupe is marked with status as "Unresolvable crosswalk"

**Steps to reproduce:**
**_Scenario 1:_**
_For eg: In the below screenshot, "VMMC_CIRC (N, DSD, Age/Sex/HIVStatus): Voluntary Circumcised, 1-4 Negative, Male" pure dedupe was never resolved and it was not resolved on Crosswalk dedupe as well._
1. Create a Pure dedupe with Crosswalk associated with it
![image](https://user-images.githubusercontent.com/24919495/106509477-b0920480-649b-11eb-9e3a-3178905252ad.png)

2. Search Crosswalk dedupe for unresolved records and verify that unresolved Pure dedupes are marked as "Unresolvable crosswalk" and the user is unable to resolve crosswalk
![image](https://user-images.githubusercontent.com/24919495/106510371-d5d34280-649c-11eb-8925-c376adc6afa7.png)

**_Scenario 2:_**
For eg: If the pure dedupe was resolved and reverted back to unresolved then crosswalk dedupe is marked as "Unresolvable crosswalk"
1. Create a Pure dedupe with Crosswalk associated with it
![image](https://user-images.githubusercontent.com/24919495/106513780-61e76900-64a1-11eb-834e-a1d7e556f953.png)
2. Resolve "VMMC_CIRC (N, DSD, Age/Sex/HIVStatus): Voluntary Circumcised, 1-4, Unknown, Male" and pure dedupe will be marked as "Resolved on Server" and shall be resolvable on Crosswalk
![image](https://user-images.githubusercontent.com/24919495/106514006-b5f24d80-64a1-11eb-8d4c-de1d82fe6e66.png)
3. Verify that the user is able to select the same data element on crosswalk and resolve the dedupe
![image](https://user-images.githubusercontent.com/24919495/106516937-cc020d00-64a5-11eb-804c-04aedc0f84d6.png)
4. Now go back to Pure dedupes and unresolve the same data element record
![image](https://user-images.githubusercontent.com/24919495/106517249-3dda5680-64a6-11eb-980f-c2b2e9088231.png)
5. Verify that Crosswalk dedupe for the same data element is locked
![image](https://user-images.githubusercontent.com/24919495/106517869-10da7380-64a7-11eb-8bca-b6fa5e76108c.png)

**Expected:**
In both scenarios 1 & 2, the Pure dedupes were unresolved whereas on Crosswalk dedupes page, Scenario 1 is unlocked and the user can still select the radio button and resolve the dedupe record and in Scneario2, the dedupe record got locked and user sees "Unresolvable crosswalk" status.

**Comment by benguaraldi** [comment]
I suspect this was resolved by the same fix as #194.  Please retest, @srihtanguturi.

**Comment by jakub-bao** [comment]
@benguaraldi We just re-tested over phone with @srihtanguturi and it's fixed. Closing.

**Comment by jakub-bao** [comment]
Re-opnening. @benguaraldi mentioned that this might be a cache issue with the SQL view we're using.
He suggests to re-test this once more tomorrow to double-check it's fixed.

**Comment by jakub-bao** [comment]
Just adding notes what's the exact test scenario:
![image](https://user-images.githubusercontent.com/47790868/106661894-c113af00-656f-11eb-9e65-25779f421041.png)
![image](https://user-images.githubusercontent.com/47790868/106661928-cb35ad80-656f-11eb-9662-23f3d952cc1c.png)
 and `1-4 Negative, Male`

**Comment by jakub-bao** [comment]
all working. closing.
