### ISSUE TITLE
Filter dedupes by agency dropdown is not showing different agency options

### ISSUE THREAD

**Issue by srihtanguturi** [pepfar-datim/datim-dedupe#197]
@benguaraldi @jakub-bao 
Environment: nr.testing.datim.org
user: interagencytester1

Filter by agency dropdown should display different agency names whereas only "All Agencies" option was displayed to the user in the agencies dropdown

![image](https://user-images.githubusercontent.com/24919495/106778543-173a2e00-6614-11eb-8ac8-47bb9c5fff79.png)

**Comment by jakub-bao** [comment]
Talked about it with @srihtanguturi & @benguaraldi over phone and concluded it's not an issue.
This appears as partner user only and partners won't have access to the app.
