### ISSUE TITLE
Wait until user selects period to trigger the query response

### ISSUE THREAD

**Issue by jason-p-pickering** [pepfar-datim/datim-dedupe#49]
Is there anyway to stop the app from attempting to load
until the period has been selected?
i think the request to the query should happen after this
because now, we get a lot of situations when people need to select a different time period as opposed to the default
otherwise, we need to tweak what the default is
which i think for TARGETs should be current fiscal year + 1
and for results...
well, not sure
but currently it is "2015Q1"

**Comment by benguaraldi** [comment]
Resolved by new app.  Closing.
