### ISSUE TITLE
Do not cache index.html

### ISSUE THREAD

**Issue by jason-p-pickering** [pepfar-datim/datim-dedupe#51]
We have a situation whereby the assess for the dedupe app are being cached.The current nginx config is set to "expires max;" for apps, and thus they will essentially never be updated (I think). 

For Dedupe, we have some cache busters to get around this, but if the index.html file is cached, then the cache busters will never kick in. 

Is there a way to cache everything "except" index.html or to set a shorter expiry date for it, maybe like 1 day? That way, at least it would be cached for a day, and then when we make updates to the app, then the users would get the new app the next day.

**Comment by dancocos** [comment]
I can look into changing the expires config and nginx updates don't cause any downtime, but FWIW the nginx caching isn't turned on. I
[root@www ~]# ls -l /var/cache/nginx/
total 0
Though since the apps behind /api Tomcat could be caching them.

**Comment by jason-p-pickering** [comment]
Yes, but that is not the problem. THe problem is 

    location /apps/ {
      root	 /usr/share/nginx;
      expires    max;
    }

whereby the index.html page gets marked as being cachable for ever.

**Comment by jason-p-pickering** [comment]
As Mark pointed out to me, index.html returns a Remote 

Address:54.175.33.95:443
Request URL:https://www.datim.org/api/apps/datim-dedupe/index.html
Request Method:GET
Status Code:304 Not Modified

What I need is

Remote Address:54.175.33.95:443
Request URL:https://www.datim.org/api/apps/datim-dedupe/index.html
Request Method:GET
Status Code:200 OK

Which will (if things have changed) bust the cache within the broswer and download new resources as needed.

**Comment by Markionium** [comment]
What also mighty have to do with it is that both test.datim and triage.datim return etags for the requested resources. Adding those might be sufficient to solve the problem.

### Triage
![image](https://cloud.githubusercontent.com/assets/2134901/7751709/a42b9254-ffdb-11e4-9732-b398385b8ec1.png)

### Prod
![image](https://cloud.githubusercontent.com/assets/2134901/7751722/b495ff30-ffdb-11e4-8d73-77fac7aa4e9c.png)

**Comment by Markionium** [comment]
Not sure if that would solve the whole issue the main thing is the 304 on the index.html

**Comment by dancocos** [comment]
Hi Mark, ETags should now be showing on Prod.

**Comment by Markionium** [comment]
The following might be one of the problems we run into. 

Chrome. Google Chrome caches HTTPS-delivered content to disk, unless the following is present:
The HTTP header Cache-Control: no-store.
ISE verified that using Google Chrome 27.0.1453.94m on Windows 7, and the Browser app in Android 2.3.6 (which is based on Chrome), HTTPS content is disk cached unless the server sends the Cache-Control: no-store header. (Source: http://securityevaluators.com/knowledge/case_studies/caching/)

Additionally the lack of caching headers on the response makes me assume that the browsers calculates the cache time based on the Date and the Last modified time according to the HTTP 1.1 spec. (Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching_FAQ and http://tools.ietf.org/html/rfc2616)

From what i've seen is that set caching headers not to cache their index.html pages. Using stuff like.

```
Cache-control:no-cache
Expires:Thu, 19 Nov 1981 08:52:00 GMT
```

While other assets like css files and javascript files get cache headers like
```
Cache-Control:max-age=7257600
Expires:Thu, 13 Aug 2015 22:46:01 GMT
```

I'm reading into it a bit more, but this looks like the way to go forward.

**Comment by jason-p-pickering** [comment]
Assuming this is OBE.
