### ISSUE TITLE
Filter irrelevant orgunits

### ISSUE THREAD

**Issue by jason-p-pickering** [pepfar-datim/datim-dedupe#52]
Comment from @ayu109,

Please address: When in dedupe, OU of user was selected by default, but user could select and see other OUs' submitted values that require dedupe. Though OUs can see data throughout OUs, the ability to dedupe is not there. 

Likely, need to filter on fields=dataViewOrganisationUnits[id]

**Comment by jason-p-pickering** [comment]
Using /api/me, we should be able to get the appropriate filter @Markionium ?

**Comment by MDHomem** [comment]
Fixed in #79
