### ISSUE TITLE
Implement an easier way to modify dedupe adjustments

### ISSUE THREAD

**Issue by jason-p-pickering** [pepfar-datim/datim-dedupe#57]
User story is here. 

https://datim.zendesk.com/agent/tickets/5927

User needs to modify duplication adjusments, but with potentially many, it can be exceedingly difficult to find the adjustment which needs to be modified. 

Suggested improvement would be a means to easily search dedupe adjustments by

1) Name of site
2) Data element
3) Mechanism

**Comment by benguaraldi** [comment]
Closing if favor of #46.
