### ISSUE TITLE
DHIS2 paging leads to a bug in the dedupe app

### ISSUE THREAD

**Issue by jason-p-pickering** [pepfar-datim/datim-dedupe#86]
While investigating another ticket, I came across this: 

![image](https://user-images.githubusercontent.com/2968061/62517985-c7b15100-b828-11e9-89a9-88cf7bf61a6f.png)

Its a single value, which should never be the case with dedupe. 

Looking further into this, it appears to be a paging related bug with 2.30, which appears to automatically page the records from the SQL view. We have implemented a server side caching mechanism with the SQL View which is used for dedupe, but this effectively gets overridden by the pager of DHIS2. 

I think the solution here is to append `&paging=false` to all requests which are made to the server by the app. This will ensure that the "normal" server side paging of the SQL function is used. 

FYI @Nhobby @benguaraldi @hkim224 

Assigning to you @tomzemp for now.

**Comment by jason-p-pickering** [comment]
After the fix in @1db3bc9, this is what that record looks like (which is correct). 

![image](https://user-images.githubusercontent.com/2968061/62531914-a873ed00-b843-11e9-9b5c-4db94d6eb96a.png)


Many thanks @tomzemp for the quick turn around. @Nhobby I am recommending an immediate deploy to production for this fix.

**Comment by Nhobby** [comment]
given the low level of risk and urgency, please deploy @jason-p-pickering.  Please work with @chuqyang to update other instances.  Please also share issue with QA team to see how we can update testing script to catch something like this going forward

**Comment by jason-p-pickering** [comment]
**Issue description:** In DHIS2 v2.30, SQL views are now paged, meaning not all results which are present in the record set are sent by the server to the client. This is a change in behavior compared to v 2.29. In the dedupe app, we have implemented a server side caching mechanism with the SQL view which is used for dedupe. However, due to the newly introduced paging in v2.30, record sets are truncated in an unpredictable fashion. 

**User impact:** Users may be presented with incorrect deduplication groups, thereby leading to user confusion. 

**Program impact:** If users were to deduplicate under the circumstances outlined above, deduplication would not be calculated correctly, leading to potential data quality issues in all systems. 

**Resolution:** Append `&paging=false` to all requests which are made to the server by the app. This will ensure that the "normal" server side paging of the SQL function is used.

**Risk assessment:** Given the impending closure of the quarter and large number of outstanding dedupes in the system, it is expected that people will begin to use the app more frequently. Under the circumstances outlined above, this will likely lead to incorrect dedupes in the system, which would propagate to downstream systems.  The risk of deployment is very low, since all that needs to be done is to deploy a new version of the app. 

**Recommended course of action:** Make the fix immediately in the app, which should be trivial.

**Comment by jason-p-pickering** [comment]
Deployed to production. Seems to fix the issue, so closing this.

**Comment by hkim224** [comment]
I shared this issue with the test team.
