### ISSUE TITLE
Add new filters to Dedupe UI

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-dedupe#89]
Per discussion with @hardingt 
Let's add new ways to filter dedupes:
1. Tech. area
2. Facility
3. Agency
4. Partner

**Comment by jason-p-pickering** [comment]
Closing this as partially implemented. Technical area and agency filter have been implemented in the UI. Pending bug  #110 for the backend--agency filter is not working under certain circumstances for DSD-TA crosswalk.
