### ISSUE TITLE
Not getting any dedupes via new SQL

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-dedupe#99]
I've deployed new Jason's SQL for `view_dedupes` to `dev.datim.org`
Trying to execute it for `USAID` but not getting any results...

`SELECT * FROM view_duplicates('XOivy2uDpMF', '2019Q3', false, 50, 1, 'RESULTS','PURE','NONE','NLV6dy7BE2O');`

However, I think there should be some...

![image](https://user-images.githubusercontent.com/47790868/71382366-a7025180-25a5-11ea-95c5-3abcad6221cc.png)

@jason-p-pickering Can you please take a look?

**Comment by jason-p-pickering** [comment]
Not an issue?

**Comment by jakub-bao** [comment]
@jason-p-pickering yeah I was connected to the wrong server (as usually :)
